### ISSUE TITLE
ハンターのランダム抽選

### ISSUE THREAD

**Issue by keepoff07** [keepoff07/HIYU_TosoGame#31]
> 1度コマンドを実行すると運営を除いたプレイヤーの中からハンターを１人だけランダムで選択される。
/toso h random（もう一度コマンドを実行するともうひとりランダムで選択される）

@rでいいと思った

**Comment by nakamurahiyu** [comment]
自分的には'random'が打ちなれてるので出来ればそのままでお願いします

**Comment by keepoff07** [comment]
[wiki](https://github.com/keepoff07/HIYU_TosoGame/wiki/Command)に追記
