### ISSUE TITLE
/toso resetについて

### ISSUE THREAD

**Issue by keepoff07** [keepoff07/HIYU_TosoGame#32]
> /toso reset を実行した際に逃走者が全員チームから追放される

**Comment by keepoff07** [comment]
@nakamurahiyu

/toso reset は初期バージョンから追加されているコマンドで、当初は

> /toso reset コマンドにより全員のインベントリーを消去し、{牢屋}へTPする（運営は除く）

そしてv1.3.0では

> > /toso resetコマンドが実行されると完全にゲーム進行が停止し、リセットされる[タイマー|運営を除く全員のインベントリー(ハンターの防具も含め)消去|

> [#16](https://github.com/keepoff07/HIYU_TosoGame/issues/16)

と聞いております。
そこに要望のない"プレイヤー情報の初期化"の機能が入っているのは、
現在チームを初期化する方法が`/toso player clear` `/toso hunter clear` しか存在せず、
「確保者」「逃走成功者」の情報を初期化する術が無い為です。
もちろんresetコマンドの"プレイヤー情報の初期化"の機能は、本件を受け削除はしますが、
その場合はどうするつもりなのかをご教授お願いします。
もし黙秘にしたい場合は「ノーコメントで」等々言っていただけると助かります。

**Comment by nakamurahiyu** [comment]
申し訳ありませんでした。またまた自分の手違いでした。OPを持っていると運営扱いされるのをすっかり....ひげさんの指摘を受け、直さないといけないところがありましたので記載します。

**Comment by keepoff07** [comment]
了解しました。

**Comment by keepoff07** [comment]
現在の/toso resetの機能です。上から順に動作します。
* スコアボードのチーム情報を初期化
* タイマーの強制停止
* サーバーにオンラインのプレイヤーに対して
  * インベントリと装備を削除する(運営以外のみ)
  * 牢屋にTPさせる(牢屋が登録されている時)
  * 逃走者へ追加する
* サイドバーを更新する

となっています。
本Issuesは一度閉じますが、なにかあれば再度開きますので遠慮なく言ってください。

**Comment by nakamurahiyu** [comment]
文章に記載し忘れてました
>/toso reset コマンドにより全員のインベントリーを消去し、{牢屋}へTPする（運営は除く）
の機能も追加しつつ、
>/toso resetコマンドが実行されると完全にゲーム進行が停止し、リセットされる[タイマー|運営を除く全員のインベントリー(ハンターの防具も含め)消去|
この機能も追加していただきたいのです....

**Comment by keepoff07** [comment]
すいません、こちらの解釈の問題かもしれませんが、
内容に矛盾が感じられるので再度確認させていただきます。

まず、
> /toso resetを実行すると、運営も含み全員を逃走者に追加し、牢屋にTPさせるというのを追加していただきたいです。

ここから追加する機能は以下の通りです。
* 運営を含む全てのプレイヤーを逃走者に追加する。
* 運営を含む全てのプレイヤーを牢屋にTPさせる。

次に
> /toso reset コマンドにより全員のインベントリーを消去し、{牢屋}へTPする（運営は除く）

ここから追加する機能は以下の通りです。
* 運営以外の全てのプレイヤーのインベントリを消去する。
* 運営以外の全てのプレイヤーを牢屋にTPさせる。

次に
> /toso resetコマンドが実行されると完全にゲーム進行が停止し、リセットされる[タイマー|運営を除く全員のインベントリー(ハンターの防具も含め)消去|

ここから追加する機能は以下の通りです。
* ゲーム進行を停止させる。
* タイマーをリセットする。
* 運営以外の全てのプレイヤーのインベントリを消去する。
  * この時防具も消去する。

そして報告で頂いた内容は
> OPを持っている人がハンターになり、/toso startのあとに/toso resetコマンドを実行しても、サイドバーは更新されますが、防具が消えない現象が起きました。(OPをはく奪すると、防具は消えていました) 

なので、修正案件としては
* 運営を含む全てのプレイヤーのインベントリを消去する。

と読み取れました。
これらの通りこちら側の解釈では少し矛盾が感じられました。
その為、最終的に以下の2点を再確認します。
* 防具も含むインベントリの削除は、運営も含むのかそうでないのか。
  * もしくは、運営は防具だけ削除されるのか。
* 牢屋にTPさせるのは、運営も含むのかそうでないのか。

回答よろしくお願いします。

**Comment by nakamurahiyu** [comment]
すみませんね....

>防具も含むインベントリの削除は、運営も含むのかそうでないのか。
もしくは、運営は防具だけ削除されるのか。

についてですが、運営は防具のみの削除です
つぎに

>牢屋にTPさせるのは、運営も含むのかそうでないのか。

については、運営は含みません

**Comment by keepoff07** [comment]
了解しました。
