### ISSUE TITLE
ヘルプについて

### ISSUE THREAD

**Issue by keepoff07** [keepoff07/HIYU_TosoGame#35]
> /toso hunter /toso toso /toso point のコマンドを実行しても、第2のヘルプに飛ばない

**Comment by keepoff07** [comment]
@nakamurahiyu

[#18](https://github.com/keepoff07/HIYU_TosoGame/issues/18)、[#27](https://github.com/keepoff07/HIYU_TosoGame/issues/27)参照。
まず#27にてコマンドの変更をしましたが、本件を受ける限り、
「変更前のコマンドが使えない」と言っているようにも感じます。
こちらの読解力不足で申し訳ありませんが、
・#27の変更は、前までの、例えば`/toso hunter ～`も残しつつ同様の機能として`/toso h ～`を追加したかったのか、
・それとも、#27はその通りコマンドの変更を行い、#18のヘルプは`/toso hunter`と入力した時のみ表示されるのか。
またはそれ以外か…ご教授お願いします。

**Comment by nakamurahiyu** [comment]
ヘルプ内容をそのまま載せてしまいますが、/tosoを実行するとまずはこのメッセージが送信され....
&a&l■ ■ ■ ■ ■ &6&lHIYUT&f_&4&lTosoGame &f<version> &a&l■ ■ ■ ■ ■
&4&l/toso start &f- &9ゲーム開始
&4&l/toso stop &f- &9ゲーム一時停止
&4&l/toso reset &f- &9ゲームリセット
&6/toso toso &f- &9逃走者選択設定
&6/toso hunter &f- &9ハンター選択設定
&6/toso timer &f- &9タイマー設定
&6/toso point &f- &9ポイント設定
&6/toso config &f- &9Config設定
&a&l■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ 
その中のコマンドを実行すると次のようなヘルプが表示されるということです....(今回は/toso toso を実行したとしましょう)
&a&l■ ■ ■ ■ ■ &6&lHIYUT&f_&4&lTosoGame &f<version> &a&l■ ■ ■ ■ ■
&6/toso t add <PLAYER> &f- &9逃走者追加
&6/toso t remove <PLAYER> &f- &9逃走者消去
&6/toso t clear <PLAYER> &f- &9逃走者情報初期化
&a&l■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■

こちらこそ説明不足で申し訳ありませんでした

**Comment by nakamurahiyu** [comment]
念の為にお伝えしておきますが、/toso tosoではなく、/toso tというコマンドを実行しますと、第二のヘルプが表示されました。↓      
&a&l■ ■ ■ ■ ■ &6&lHIYUT&f_&4&lTosoGame &f<version> &a&l■ ■ ■ ■ ■
&6/toso t add <PLAYER> &f- &9逃走者追加'
&6/toso t remove <PLAYER> &f- &9逃走者消去'
&6/toso t clear <PLAYER> &f- &9逃走者情報初期化
&a&l■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■

**Comment by keepoff07** [comment]
了解しました。

**Comment by keepoff07** [comment]
例として、`/toso hunter`で専用のヘルプメッセージが表示され、
`/toso h`では従来のヘルプメッセージを表示するようにしました。
`/toso toso`なども同様です。
