### ISSUE TITLE
1.7.2-1.8.3

### ISSUE THREAD

**Issue by keepoff07** [keepoff07/HIYU_TosoGame#44]
> 1.7.2-1.8.3のバージョンまで対応できる

現在の問題として、1.8でのサイドバーの読み込みの遅さが問題になっています。
#45を追加するついでにサイドバーの処理を改善してみようと思います。
（どこまでできるかわかりませんが…）

**Comment by nakamurahiyu** [comment]
すみません。今気づいたのですが、なぜ1.7.2-1.8.3に限定してしまったのか....1.7.2-1.8.X対応できるようでしたらお願いします。

**Comment by keepoff07** [comment]
了解しました。
今のところ1.8.4までリリースされていますが、1.8系列は全て互換性があるようなで大丈夫そうです。

**Comment by keepoff07** [comment]
サイドバーの処理を変更し、1.8.xでもあまり違和感なくスコアボードの更新が出来るようになりました。
また、現在実装されている機能をある程度試験しましたが、1.8.xでも問題なく動作することを確認しました。
