### ISSUE TITLE
エンディング機能

### ISSUE THREAD

**Issue by keepoff07** [keepoff07/HIYU_TosoGame#48]
* コマンドを実行することで、プレイヤー全員にEDを表示する
* EDはEndPoem
  * TheENDにTPさせてポータルに強制的入らせる
* サウンドも流せるようにする
  * ~~BukkitAPI、PacketではSEがフェードアウトしてしまう~~
    * ~~playsoundコマンドで再生する~~
  * サウンドはconfigで指定
  * MusicGuiとの競合ですが、別ディメンションなので流してる曲は消えると予想

**Comment by keepoff07** [comment]
> BukkitAPI、PacketではSEがフェードアウトしてしまう
再確認したところ、こちらで実験した時にエンド側からのポータルの下に足場が無かったため
プレイヤーがそのまま落下していき音がフェードアウトしているように感じたようでした。
足場とポータルを生成することでこれを回避出来ました。
（playsoundと同じPacket使って動作が違うから謎だったけど、これで解決しました）
Packetでも可能だとわかったのでこちらの方法でいこうとおもいます。

**Comment by nakamurahiyu** [comment]
了解です

**Comment by keepoff07** [comment]
[wiki](https://github.com/keepoff07/HIYU_TosoGame/wiki/Command)に追記
