### ISSUE TITLE
逃走成功ミッション

### ISSUE THREAD

**Issue by keepoff07** [keepoff07/HIYU_TosoGame#59]
> * 【/toso mission success】コマンドを実行することでアイテム欄に特別なエメラルドブロックと石のボタンが配布される
>   * エメラルドブロックのどこかの面にボタン（石）を付け、それを逃走者が押すと逃走成功者となり逃走成功者場所にTPされる
>     * グローバルメッセージを出す(例:%player%が逃走成功しました(Configで編集可能))
>       * 音を設定可能にする
>   * サーバーが停止(【/stop】)もしくは【/toso reset】コマンドが実行されると設置したブロックと石のボタンが消される
>   * 【toso mission success book】コマンドを実行するとミッション内容を本で通知される(Configで内容編集可能)
>     * 音を設定可能にする

**Comment by keepoff07** [comment]
(私事)Skypeの方あまりログインできそうにないのでこちらで相談させていただきます。
***
> コマンドを実行することでアイテム欄に特別なエメラルドブロックと石のボタンが配布される

配布されるのはコマンドを実行した運営者だけであってますか？

> 【toso mission success book】コマンドを実行するとミッション内容を本で通知される

他のミッションにも関係することなのですが、本関連のコマンドを別途で考えてみたので提案させていただきます。
https://gist.github.com/keepoff07/f061c6ae2227b5ed31e3
`リンク先はGithub内のサービスであるGistです。Githubと同様にコメントできると思います。`
あくまで「このほうが使いやすい？」みたいなノリの提案なので、依頼通りの`/toso mission success book`でも可能です。

**Comment by nakamurahiyu** [comment]
>>コマンドを実行することでアイテム欄に特別なエメラルドブロックと石のボタンが配布される
>配布されるのはコマンドを実行した運営者だけであってますか？

あっています

>>【toso mission success book】コマンドを実行するとミッション内容を本で通知される
>他のミッションにも関係することなのですが、本関連のコマンドを別途で考えてみたので提案させていただきます。
https://gist.github.com/keepoff07/f061c6ae2227b5ed31e3
リンク先はGithub内のサービスであるGistです。Githubと同様にコメントできると思います。
あくまで「このほうが使いやすい？」みたいなノリの提案なので、依頼通りの/toso mission success bookでも可能です。

ご提案ありがとうございます。URL先の提案でお願いいたします。(一部変更希望を上記のURLのほうでコメントいたしましたのでご確認をお願いします)
コマンドのほうを覚えきれ宇ないと思いますので、念のためにヘルプのほうにも登録していただけると嬉しいです。

第一ヘルプ
&a&l■ ■ ■ ■ ■ &6&lHIYUT&f_&4&lTosoGame &f &a&l■ ■ ■ ■ ■
&4&l/toso start &f- &9ゲーム開始
&4&l/toso stop &f- &9ゲーム一時停止
&4&l/toso reset &f- &9ゲームリセット
&6/toso toso &f- &9逃走者選択設定
&6/toso hunter &f- &9ハンター選択設定
&6/toso mission &f- &9ミッション設定
&6/toso timer &f- &9タイマー設定
&6/toso point &f- &9ポイント設定
&6/toso config &f- &9Config設定
&a&l■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ 

第二ヘルプ
&a&l■ ■ ■ ■ ■ &6&lHIYUT&f_&4&lTosoGame &f &a&l■ ■ ■ ■ ■
&6/toso book &f- &9本配布
&a&l■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■

第３ヘルプ
&a&l■ ■ ■ ■ ■ &6&lHIYUT&f_&4&lTosoGame &f &a&l■ ■ ■ ■ ■
&6/toso book give <PLAYER> &f- &9本配布
&6/toso book reset <PLAYER> &f- &9本再配布
&6/toso book send <TITLE> &f- &9ミッション配布
&a&l■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■

**Comment by nakamurahiyu** [comment]
文字制限のようなものが見受けられましたので投稿を分けたいと思います

第一ヘルプ
&a&l■ ■ ■ ■ ■ &6&lHIYUT&f_&4&lTosoGame &f &a&l■ ■ ■ ■ ■
&4&l/toso start &f- &9ゲーム開始
&4&l/toso stop &f- &9ゲーム一時停止
&4&l/toso reset &f- &9ゲームリセット
&6/toso toso &f- &9逃走者選択設定
&6/toso hunter &f- &9ハンター選択設定
&6/toso mission &f- &9ミッション設定
&6/toso timer &f- &9タイマー設定
&6/toso point &f- &9ポイント設定
&6/toso config &f- &9Config設定
&a&l■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ 

第二ヘルプ
&a&l■ ■ ■ ■ ■ &6&lHIYUT&f_&4&lTosoGame &f &a&l■ ■ ■ ■ ■
&6/toso book &f- &9本配布
&a&l■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■

第３ヘルプ
&a&l■ ■ ■ ■ ■ &6&lHIYUT&f_&4&lTosoGame &f &a&l■ ■ ■ ■ ■
&6/toso book give <PLAYER> &f- &9本配布
&6/toso book reset <PLAYER> &f- &9本再配布
&6/toso book send <TITLE> &f- &9ミッション配布
&a&l■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■

**Comment by keepoff07** [comment]
了解しました
