### ISSUE TITLE
防具固定機能

### ISSUE THREAD

**Issue by keepoff07** [keepoff07/HIYU_TosoGame#6]
> ハンターとして指名されると、防具などを着させられる(脱げない)。

**Comment by keepoff07** [comment]
[wiki](https://github.com/keepoff07/HIYU_TosoGame/wiki/Function-Hunter)に追記

**Comment by keepoff07** [comment]
> 着させられる
ってことは自動で装備させるという…？(アイテムの指定どうするんだろ)

**Comment by nakamurahiyu** [comment]
ここでコメントしていいかわかりませんけど、自動装備ということです。（全ダイヤモンド装備）

**Comment by keepoff07** [comment]
了解しました。

**Comment by keepoff07** [comment]
ハンターに追加されるとダイヤモンドのフル装備をさせ、
逆にハンターから削除されると装備を削除されます。

**Comment by keepoff07** [comment]
[wiki](https://github.com/keepoff07/HIYU_TosoGame/wiki/Function-Hunter)に追記
