### ISSUE TITLE
エリア拡張ミッション

### ISSUE THREAD

**Issue by keepoff07** [keepoff07/HIYU_TosoGame#60]
> * 【/toso mission area】コマンドを実行することでアイテム欄に普通のチェストと特別なミッションチェストが配布される
> * ミッションチェストを置くと普通のチェストとはConfigで設定したアイテムが中に入れられる
> * >Configで設定したアイテム< をチェストから取り出し、それを鉄ドア前の床にダイヤブロックがある所に経つとその扉が解放される
>   * グローバルメッセージを出す(例:%player%によりエリアが拡張された(Configで編集可能))
>     * 音を設定可能にする
>   * サーバーが停止(【/stop】)もしくは【/toso reset】コマンドが実行されるとミッションチェストが普通のチェストになり、中身が残っていた場合は消される
>   * 【toso mission area book】コマンドを実行するとミッション内容を本で通知される(Configで内容編集可能)
>     * 音を設定可能にする

**Comment by keepoff07** [comment]
> ミッションチェストを置くと普通のチェストとはConfigで設定したアイテムが中に入れられる

よくわからないので詳しい解説お願いします。

> それを鉄ドア前の床にダイヤブロックがある所に経つとその扉が解放される 

これは逃走者が「取り出したアイテム」を持って鉄ドア前のダイヤブロックに立つと…という解釈であっていますか？

> ミッションチェストが普通のチェストになり、中身が残っていた場合は消される

チェスト自体はそのまま放置で大丈夫ですか？

**Comment by nakamurahiyu** [comment]
>>ミッションチェストを置くと普通のチェストとはConfigで設定したアイテムが中に入れられる
>よくわからないので詳しい解説お願いします。

申し訳ございません、タイピングミスです
訂正:
普通のチェストを設置しても何も起こらないが、ミッションチェストを設置すると、Configで設定したアイテムが中に入れられる(入れられる個数configにて編集可(逃走者が取り出せるアイテム個数をConfigにて編集化))

>>それを鉄ドア前の床にダイヤブロックがある所に経つとその扉が解放される
>これは逃走者が「取り出したアイテム」を持って鉄ドア前のダイヤブロックに立つと…という解釈であっていますか？

あっています

>>ミッションチェストが普通のチェストになり、中身が残っていた場合は消される
>チェスト自体はそのまま放置で大丈夫ですか？

やはり壊し忘れなどが怖いため、チェスト（特別なチェスト & 普通のチェスト）事消えるようにお願いいたします


/toso bookコマンドを提案してくださったかと思うのですが

>【toso mission area book】コマンドを実行するとミッション内容を本で通知される(Configで内容編集可能)

これも含め/toso book send <TITLE>
コマンドにて通知できるようにしていただけますでしょうか？

**Comment by keepoff07** [comment]
了解しました

**Comment by keepoff07** [comment]
@nakamurahiyu ミッション用チェストおよびミッションの動作について、こちらで事前に説明しておきます。
* チェストは1つしか設置できません
* [mission.yml](https://github.com/keepoff07/HIYU_TosoGame/blob/master/HIYU_TosoGame/mission.yml)にて中身を設定できます
* 上のリンクよりmission.ymlを見ていただくと分かる通り、複数の不特定のアイテムを入れることができます。
  * これらの設定した全てのアイテムがエリア拡張ミッションのキーアイテムとして使用できます。
* キーアイテムはミッション用チェストを設置してから機能します(負荷軽減のため)。
* キーアイテムは手に持ってダイヤブロックの上に立たなければ機能しません。
* グローバルメッセージを設定できます。
* ダイヤブロックと鉄ドアの位置の参考です
  * (周りの他のブロックは位置関係をわかりやすくするために設置されたものです。ミッションとは関係ありません)
  * ![](https://gyazo.com/3e2e9be7ce8dc4ad0b22dea719a84b52.png)
* ミッションの通知は/toso bookコマンドで自由にできるので、ここでは割愛します。
* ミッション用チェスト破壊時には中のアイテムが飛び散らすことなく破壊できます。
* サーバーが停止もしくは【/toso reset】コマンド時にはミッション用チェストのみ破壊されます。
  * この時の破壊も中のアイテムは飛び散りません。

希望内容と差異がある場合はコメントお願いします。

**Comment by Hiyuuu** [comment]
- チェストが消滅するまでの時間を設定（メッセージあり）。【`/toso mission Area <TIME>`】

    - 設置したチェストが消滅するまでに阻止できなかった場合（上記のコマンドで時間が指定されている場合で）、メッセージとともにチェストが消える。
