### ISSUE TITLE
1.8 ～ 1.11対応

### ISSUE THREAD

**Issue by Hiyuuu** [keepoff07/HIYU_TosoGame#84]
1.8 ～ 1.11への対応化をする。（手が届けば1.8～1.11、 1.9～1.11、1.10～1.11、1.11それぞれのモードに切り替えれるようにする)

**Comment by keepoff07** [comment]
1.8 ～ 1.11の範囲で対応化を検討します。

> 手が届けば1.8～1.11、 1.9～1.11、1.10～1.11、1.11それぞれのモードに切り替えれるようにする

こちらについては、1つのプラグインでバージョン対応を切り替えるなら、対応バージョンが異なる4つのプラグインを作った方がいいくらいだと思うので、見送らせていただきます。

**Comment by Hiyuuu** [comment]
了解致しました

**Comment by Hiyuuu** [comment]
大変お手数おかけいたしますが、サーバーの構成を見直したため、バージョンを1.11.Xにしていただけますでしょうか。
