### ISSUE TITLE
逃走中マップ指定の概念を追加

### ISSUE THREAD

**Issue by Hiyuuu** [keepoff07/HIYU_TosoGame#97]
- 【`/toso map add <MAPNAME>`】及び【`/toso map remove <MAPNAME>`】コマンドにてマップの追加/削除が出来る。

- 【`/toso map <MAPNAME> <TIME>`】コマンドにて<TIME>の時間カウントダウンし、ゲームマップを切り替えると同時にサーバー内のプレイヤーを指定したワールドの待機に移動する。（Config設定可）

- 【`/toso p set [Jail,Gath,Rev,etc...]  <MAPNAME> <NUMBER>`】コマンドにてマップごとにポイントを**複数**設定できる。（複数設定されていればランダムスポーンになる）

- サイドバーに現在のマップ名を表示する。（マップ名、<MAPNAME>)

- 【`/toso  tp map <MAPNAME> <PLAYER>`】コマンドにてプレイヤーが指定されていなければ実行者が指定マップの待機に移動される。

追記

- 【`/toso map list`】コマンドにて登録したマップリストを表示できる。

 - 【`/toso mission zombie add(remove) <MAP> <NUMBER>`】コマンドにてそのマップの都度にボットハンター出現位置を複数設定できる。

**Comment by keepoff07** [comment]
マップ機能が大半出来たので、忘れないうちに細かい仕様を挙げておきます。

- 【`/toso map add <MAPNAME>`】について
  - `<MAPNAME>`はconfigのパスとしてそのまま使用します
  - またサイドバーにもそのまま使用します
  - なので日本語も使えますが長いのは非推奨です
- 【`/toso map remove <MAPNAME>`】について
  - 選択中のマップを削除した場合は選択解除されます
- 【`/toso map <MAPNAME> <TIME>`】について
  - `message.yml`に以下のアナウンス設定を追加
    - `MapTeleportAnnounce.TimerStart`
    - `MapTeleportAnnounce.Timer`
    - `MapTeleportAnnounce.TimerEnd`
    - `Message`に`%target`を使用すると指定したマップ名に置き換えます
  - マップ移動のタイマーは移動完了まで停止できません
  - コマンド実行時にテレポート地点を決めるので、カウント中に編集はできません
- 【`/toso p set <jail|rev|suc|gath|wait> <MAPNAME> <NUMBER>`】について
  - `<NUMBER>`には正の数を使用してください
  - 既に使用されている`<NUMBER>`を指定すると上書きされます
  - 複数地点登録に応じて勝手に【`/toso p remove`】を追加しました
  - また【`/toso tp`】もマップ・地点・番号を指定するように勝手に修正しました
- サイドバーについて
  - `sidebar.yml`に以下の設定を追加
    - `SelectMapDisplay`
      - `MoneyDisplay`同様にただの表示です
    - `SelectMap`
      - 選択中のマップ名を`%s`で表示します
    - `UnSelectedMap`
      - マップ未選択時の表示です
